# This is a basic workflow to help you get started with Actions

name: CD
env:
  DESTINATION: 'Webapp'

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre:
    runs-on: ubuntu-latest4
    steps:
      - name: Show where is triggered from
        run: |
          echo d-lama-webapp ci/cd pipeline is triggered.
  
  cd:
    needs:
      - pre
    uses: d-lama/ops-d-lama-service/.github/workflows/d-lama-webapp-cd.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}