# This is a basic workflow to help you get started with Actions

name: CI
env:
  DESTINATION: 'Webapp'

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Show where is triggered from
        run: |
          echo d-lama-webapp ci/cd pipeline is triggered.

  ci:
    needs:
      - pre
    uses: d-lama/ops-d-lama-service/.github/workflows/d-lama-webapp-ci.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PP_DLAMA_TOKEN: ${{ secrets.PP_DLAMA_TOKEN }}
      